<a href="https://colab.research.google.com/github/tu22014/EU_M_Math-Repository/blob/main/Chap06_Cm_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#ライブラリのインポート
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mp1
import seaborn as sns
sns.set()
%matplotlib inline

#少数第3位まで表記
%precision 3

import requests
import zipfile
from io import StringIO
import io


zip_file_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00356/student.zip'

r = requests.get(zip_file_url, stream=True)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

#数学のデータを読み込む
student_data_math = pd.read_csv('student-mat.csv', sep=';')

student_data_math.groupby(['age', 'sex'])['G1'].mean().unstack().dropna()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000